version: '3'

services:
  superset:
      build:
        context: ./superset
        dockerfile: dockerfile
      container_name: superset
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_EMAIL=admin@superset.com
        - ADMIN_PASSWORD=admin
      ports:
        - '8088:8088'
      volumes:
        - superset_vol_test:/app
        - ./superset-frontend:/app/superset-frontend
  superset-node:
    image: node:16
    container_name: superset_node
    command: ["/app/docker/docker-frontend.sh"]
    depends_on: 
      - superset
    volumes: 
      - superset_vol_test:/app
      - ./docker:/app/docker
      # - ./superset-frontend:/app/superset-frontend
      
volumes:
  superset_vol_test: