
version: '3'

services:
  superset:
    image: tjdetwill007/mycustom_superset:latest
    container_name: superset
    command: ["/home/run.sh"]
    ports:
      - "8088:8088"
    volumes:
      - ./run.sh:/home/run.sh

